// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudBlazorWeb.Infrastructure.Database.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MudBlazorWeb.Infrastructure.Database.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406233749_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MudBlazorWeb.Features.Contact.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastAttemptedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("SentOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Messages", "system");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3425ce6-67e6-4318-b522-920f2c96fa41"),
                            AttemptCount = 0,
                            Body = "This is a test message.",
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "john.doe@example.com",
                            IsDeleted = false,
                            MaxRetries = 3,
                            Name = "John Doe",
                            SentOn = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Subject = "Hello"
                        },
                        new
                        {
                            Id = new Guid("e3425ce6-67e6-4318-b522-920f2c96fa42"),
                            AttemptCount = 0,
                            Body = "This is another test message.",
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "jane.smith@example.com",
                            IsDeleted = false,
                            MaxRetries = 3,
                            Name = "Jane Smith",
                            SentOn = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Subject = "Hi"
                        });
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Posts.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.PrimitiveCollection<List<string>>("Likes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalViews")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Posts", "content");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a202a02-654c-4e2e-9730-a30174d5eb41"),
                            Author = "John Doe",
                            Category = "General",
                            Content = "This is a test message.",
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This is the first post.",
                            Heading = "First Post Heading",
                            IsDeleted = false,
                            PostedOn = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "First Post",
                            TotalViews = 0,
                            UserId = "seed-user-1"
                        },
                        new
                        {
                            Id = new Guid("6a202a02-654c-4e2e-9730-a30174d5eb42"),
                            Author = "Jane Smith",
                            Category = "General",
                            Content = "This is another test message.",
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This is the second post.",
                            Heading = "Second Post Heading",
                            IsDeleted = false,
                            PostedOn = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Second Post",
                            TotalViews = 0,
                            UserId = "seed-user-2"
                        });
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Pricing.Domain.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Packages", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d1"),
                            Code = "INDV-1E-MTH",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1 educator",
                            IsDeleted = false,
                            Name = "Individual Educator",
                            Price = "R75.00",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d2"),
                            Code = "INDV-1E-2YR",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1 educator",
                            IsDeleted = false,
                            Name = "Individual Educator",
                            Price = "R45.00",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d3"),
                            Code = "SCH-20E-MTH",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Up to 20 educators",
                            IsDeleted = false,
                            Name = "School Sign On",
                            Price = "R650.00",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d4"),
                            Code = "SCH-20E-2YR",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Up to 20 educators",
                            IsDeleted = false,
                            Name = "School Sign On",
                            Price = "R425.00",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d5"),
                            Code = "SCH-40E-MTH",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Up to 40 educators",
                            IsDeleted = false,
                            Name = "School Sign On",
                            Price = "R900.00",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d6"),
                            Code = "SCH-40E-2YR",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Up to 40 educators",
                            IsDeleted = false,
                            Name = "School Sign On",
                            Price = "R650.00",
                            Type = 2
                        });
                });

            modelBuilder.Entity("MudBlazorWeb.Features.UserSessions.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AbsoluteExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdleDuration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastAccessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserStateVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b93dd09-a846-43c5-a01e-4ea9a68ec5e1"),
                            AbsoluteExpiresOn = new DateTimeOffset(new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresOn = new DateTimeOffset(new DateTime(2026, 3, 1, 0, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdleDuration = 30,
                            IsActive = true,
                            IsDeleted = false,
                            IsExpired = false,
                            LastAccessedOn = new DateTimeOffset(new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SessionTokenHash = "B8C7F7B607DCCC71B797AFEB056F2FB306BAD288AFD943334C2FA97BE7AAEB82",
                            UserId = "user123",
                            UserStateVersion = "seed-version-1"
                        },
                        new
                        {
                            Id = new Guid("4b93dd09-a846-43c5-a01e-4ea9a68ec5e2"),
                            AbsoluteExpiresOn = new DateTimeOffset(new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresOn = new DateTimeOffset(new DateTime(2026, 3, 1, 0, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdleDuration = 45,
                            IsActive = true,
                            IsDeleted = false,
                            IsExpired = false,
                            LastAccessedOn = new DateTimeOffset(new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SessionTokenHash = "EC6843B0FBD9D71CB28F4AF7005812CC5A9B95C8F162445BB669F1B5CC830EC1",
                            UserId = "user456",
                            UserStateVersion = "seed-version-2"
                        });
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Users.Domain.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Certifications", "users");
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Users.Domain.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Responsibilities")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StartDate")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs", "users");
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Users.Domain.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Qualifications", "users");
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Avatar")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("text");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<string>("EmailVerificationTokenExpiry")
                        .HasColumnType("text");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Hobbies")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetTokenExpiry")
                        .HasColumnType("text");

                    b.Property<string>("Skills")
                        .HasColumnType("text");

                    b.Property<string>("TelephoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b93dd09-a846-43c5-a01e-4ea9a68ec5e1"),
                            Avatar = 0,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "johndoe@example.com",
                            EmailVerified = false,
                            FirstName = "John",
                            HashedPassword = "hashedpassword123",
                            IsDeleted = false,
                            LastName = "Doe",
                            Name = "John Doe",
                            PackageId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserType = 0,
                            Username = "johndoe"
                        },
                        new
                        {
                            Id = new Guid("4b93dd09-a846-43c5-a01e-4ea9a68ec5e2"),
                            Avatar = 0,
                            CreatedBy = "Seeder",
                            CreatedOn = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmailAddress = "janesmith@example.com",
                            EmailVerified = false,
                            FirstName = "Jane",
                            HashedPassword = "hashedpassword123",
                            IsDeleted = false,
                            LastName = "Smith",
                            Name = "Jane Smith",
                            PackageId = new Guid("00000000-0000-0000-0000-000000000000"),
                            UserType = 0,
                            Username = "janesmith"
                        });
                });

            modelBuilder.Entity("MudBlazorWeb.Infrastructure.Database.Postgres.Common.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AuditUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("jsonb");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyValues")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Audits", "audit");
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Users.Domain.Certification", b =>
                {
                    b.HasOne("MudBlazorWeb.Features.Users.Domain.User", null)
                        .WithMany("Certifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Users.Domain.Job", b =>
                {
                    b.HasOne("MudBlazorWeb.Features.Users.Domain.User", null)
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Users.Domain.Qualification", b =>
                {
                    b.HasOne("MudBlazorWeb.Features.Users.Domain.User", null)
                        .WithMany("Qualifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MudBlazorWeb.Features.Users.Domain.User", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Jobs");

                    b.Navigation("Qualifications");
                });
#pragma warning restore 612, 618
        }
    }
}
