# escape=`
ARG BASE_TAG=windowsservercore-ltsc2019

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0-preview-${BASE_TAG} AS build
WORKDIR /src
COPY . .
RUN dotnet publish "WebServer/WebServer.csproj" -c Release -o C:/app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0-preview-${BASE_TAG}
WORKDIR /app
COPY --from=build C:/app/publish/ .
EXPOSE 80
ENTRYPOINT ["dotnet", "WebServer.dll"]
