// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudBlazorWeb.Infrastructure.Database.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MudBlazorWeb.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311204749_AddAuditDataToPackagesData")]
    partial class AddAuditDataToPackagesData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MudBlazorWeb.Features.Pricing.Domain.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Packages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d1"),
                            Code = "INDV-1E-MTH",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1 educator",
                            IsDeleted = false,
                            Name = "Individual Educator",
                            Price = "R75.00",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d2"),
                            Code = "INDV-1E-2YR",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1 educator",
                            IsDeleted = false,
                            Name = "Individual Educator",
                            Price = "R45.00",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d3"),
                            Code = "SCH-20E-MTH",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Up to 20 educators",
                            IsDeleted = false,
                            Name = "School Sign On",
                            Price = "R650.00",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d4"),
                            Code = "SCH-20E-2YR",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Up to 20 educators",
                            IsDeleted = false,
                            Name = "School Sign On",
                            Price = "R425.00",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d5"),
                            Code = "SCH-40E-MTH",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Up to 40 educators",
                            IsDeleted = false,
                            Name = "School Sign On",
                            Price = "R900.00",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("10905436-1671-4900-9d0e-6fced3fbd3d6"),
                            Code = "SCH-40E-2YR",
                            CreatedBy = "System",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Up to 40 educators",
                            IsDeleted = false,
                            Name = "School Sign On",
                            Price = "R650.00",
                            Type = 2
                        });
                });

            modelBuilder.Entity("MudBlazorWeb.Infrastructure.Database.Postgres.Common.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AuditUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChangedColumns")
                        .HasColumnType("jsonb");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyValues")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Audits", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
